#!/bin/bash

unset PYTHONPATH

fullpath=`readlink -f $0`
pathdir=`dirname $fullpath`
myenv=/home/gbt7/pipeline/gridder/bin/activate

if [ -e $myenv ]; then
    source $myenv
else
    echo Not at GBT, good luck. Hope your environment has been set.
fi

STAT_FILE="/home/scratch/pipeline/gridder.log"
if [ -w $STAT_FILE ]; then
    export LC_TIME="en_US.UTF-8"; echo `whoami`,`date`,`uname -n`,`pwd`,$fullpath $* >> $STAT_FILE
fi

PYTHONPATH=${pathdir}
export PYTHONPATH

python ${pathdir}/gbtgridder.py $*

