#!/bin/bash

unset PYTHONPATH

fullpath=`readlink -f $0`
pathdir=`dirname $fullpath`
myenv=/home/gbt7/pipeline/gridder/bin/activate

if [ -e $myenv ]; then
    source $myenv
    STAT_FILE="/home/scratch/pipeline/gridder.log"
else
    STAT_FILE="/tmp/gbtgridder.log"
    touch $STAT_FILE
    chmod 666 $STAT_FILE
    echo Not at GBT, good luck. Hope your python environment has been set.
fi
echo See $STAT_FILE for messages

if [ -w $STAT_FILE ]; then
    export LC_TIME="en_US.UTF-8"; echo `whoami`,`date`,`uname -n`,`pwd`,$fullpath $* >> $STAT_FILE
fi

PYTHONPATH=${pathdir}
export PYTHONPATH

python ${pathdir}/gbtgridder.py $*

